#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-ecommerce-nextjs"
main = ".worker-next/index.mjs"
account_id="6ea501058781ea3447393e05a0296f58"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "nextjs-ecommerce"
database_id = "9183408c-b92a-4ac9-a2e3-e8f178b3ff4d"