#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-ecommerce-nextjs"
main = ".worker-next/index.mjs"
account_id="6ea501058781ea3447393e05a0296f58"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-ecommerce-nextjs"
database_id = "b2fe3e0e-3589-4174-8fe8-a0e6c26a8340"